// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: 'us-east-1',
  aws_cognito_identity_pool_id:
    'us-east-1:8fdfe003-49f7-4071-9720-46f0fadb7f00',
  aws_cognito_region: 'us-east-1',
  aws_user_pools_id: 'us-east-1_eNGsUnFOG',
  aws_user_pools_web_client_id: '3deqam30mtqgick9umueehtq21',
  oauth: {},
  aws_appsync_graphqlEndpoint:
    'https://5oz23mu3x5bvzbxhchckqukahq.appsync-api.us-east-1.amazonaws.com/graphql',
  aws_appsync_region: 'us-east-1',
  aws_appsync_authenticationType: 'AMAZON_COGNITO_USER_POOLS',
  aws_user_files_s3_bucket: 'weekendplaygroundproductcsvuploadstorage-develop',
  aws_user_files_s3_bucket_region: 'us-east-1',
};

export default awsmobile;
